#!/usr/bin/env python3
"""
对拍验证脚本 - Step3 vs Baseline Validation

This script validates Step3 adaptive sampling by comparing it with Step2 baseline
using the SAME smart alphas generated by Step3.

Dual Validation:
1. Traditional: Point-by-point metrics comparison (Q_Y, Q_W', Q_X', etc.)
2. Physical: Phase transition detection accuracy (α_c, gradients, consistency)
"""

import sys
import json
import numpy as np
from pathlib import Path

# Add parent directory to path to import PhaseTransitionAnalyzer
sys.path.append(str(Path(__file__).parent.parent))
from phase_transition_analyzer import PhaseTransitionAnalyzer


def load_smart_alphas(npy_path: Path) -> np.ndarray:
    """Load smart alphas from .npy file"""
    alphas = np.load(npy_path)
    print(f"[Smart Alphas Loaded] {len(alphas)} points from {npy_path}")
    print(f"  Range: [{alphas.min():.2f}, {alphas.max():.2f}]")
    return alphas


def load_results(json_path: Path) -> dict:
    """Load results from JSON file"""
    with open(json_path, 'r') as f:
        results = json.load(f)
    print(f"[Results Loaded] {len(results)} alpha values from {json_path}")
    return results


def traditional_comparison(step3_results: dict, baseline_results: dict,
                          tolerance: float = 0.10) -> dict:
    """
    Traditional point-by-point comparison

    Args:
        step3_results: Step3 results dict {alpha_str: {metrics}}
        baseline_results: Baseline results dict {alpha_str: {metrics}}
        tolerance: Relative error tolerance (default 10%)

    Returns:
        comparison_dict with errors and status
    """
    print("\n" + "="*80)
    print("TRADITIONAL POINT-BY-POINT COMPARISON")
    print("="*80)

    metrics = ['Q_Y_mean', 'Q_W_prime_mean', 'Q_X_prime_mean', 'Q_W_mean', 'Q_X_mean']

    # Collect all alphas (should be same for both)
    step3_alphas = sorted([float(k) for k in step3_results.keys()])
    baseline_alphas = sorted([float(k) for k in baseline_results.keys()])

    # Find common alphas
    common_alphas = sorted(set(step3_alphas) & set(baseline_alphas))

    if len(common_alphas) < len(step3_alphas):
        print(f"⚠ Warning: Only {len(common_alphas)}/{len(step3_alphas)} alphas in common")

    # Calculate errors for each alpha and metric
    errors = {alpha: {} for alpha in common_alphas}
    max_errors = {m: 0.0 for m in metrics}

    for alpha in common_alphas:
        alpha_str = str(alpha)
        step3_data = step3_results[alpha_str]
        baseline_data = baseline_results[alpha_str]

        for metric in metrics:
            step3_val = step3_data[metric]
            baseline_val = baseline_data[metric]

            # Calculate relative error
            if baseline_val > 1e-6:
                rel_error = abs(step3_val - baseline_val) / baseline_val
            else:
                rel_error = abs(step3_val - baseline_val)

            errors[alpha][metric] = rel_error
            max_errors[metric] = max(max_errors[metric], rel_error)

    # Print summary table
    print(f"\nTesting {len(common_alphas)} alpha points with {tolerance*100:.0f}% tolerance\n")

    print("Max Relative Errors:")
    print(f"{'Metric':<20} {'Max Error':<12} {'Status'}")
    print("-" * 45)

    all_pass = True
    for metric in metrics:
        error = max_errors[metric]
        status = "✅ PASS" if error <= tolerance else "❌ FAIL"
        if error > tolerance:
            all_pass = False
        print(f"{metric:<20} {error*100:>8.2f}%   {status}")

    # Calculate statistics
    all_errors = []
    for alpha in common_alphas:
        for metric in metrics:
            all_errors.append(errors[alpha][metric])

    mean_error = np.mean(all_errors)
    max_error = np.max(all_errors)
    std_error = np.std(all_errors)

    print(f"\nStatistics across all metrics and alphas:")
    print(f"  Mean error: {mean_error*100:.2f}%")
    print(f"  Max error:  {max_error*100:.2f}%")
    print(f"  Std dev:    {std_error*100:.2f}%")

    print(f"\n{'='*80}")
    if all_pass:
        print("✅ TRADITIONAL VALIDATION PASSED")
    else:
        print("❌ TRADITIONAL VALIDATION FAILED")
    print("="*80)

    return {
        'errors': errors,
        'max_errors': max_errors,
        'mean_error': mean_error,
        'max_error': max_error,
        'std_error': std_error,
        'passed': all_pass,
        'num_points': len(common_alphas)
    }


def phase_transition_comparison(step3_results: dict, baseline_results: dict,
                                alpha_tolerance: float = 0.2,
                                gradient_tolerance: float = 0.20) -> dict:
    """
    Physical phase transition comparison

    Args:
        step3_results: Step3 results dict
        baseline_results: Baseline results dict
        alpha_tolerance: Tolerance for α_c difference
        gradient_tolerance: Tolerance for gradient relative error

    Returns:
        comparison_dict with phase analysis
    """
    print("\n" + "="*80)
    print("PHYSICAL PHASE TRANSITION COMPARISON")
    print("="*80)

    # Extract alphas
    step3_alphas = np.array(sorted([float(k) for k in step3_results.keys()]))
    baseline_alphas = np.array(sorted([float(k) for k in baseline_results.keys()]))

    # Analyze both datasets
    print("\n[Analyzing Step3 Results...]")
    step3_analyzer = PhaseTransitionAnalyzer(step3_alphas, step3_results)
    step3_phase = step3_analyzer.detect_phase_transition_enhanced()

    print("\n[Analyzing Baseline Results...]")
    baseline_analyzer = PhaseTransitionAnalyzer(baseline_alphas, baseline_results)
    baseline_phase = baseline_analyzer.detect_phase_transition_enhanced()

    # Compare phase transition characteristics
    step3_ac = step3_phase['alpha_c']
    baseline_ac = baseline_phase['alpha_c']
    ac_diff = abs(step3_ac - baseline_ac)

    step3_grad = step3_phase['gradient']
    baseline_grad = baseline_phase['gradient']
    grad_error = abs(step3_grad - baseline_grad) / baseline_grad if baseline_grad > 1e-6 else 0.0

    step3_cons = step3_phase['consistency']
    baseline_cons = baseline_phase['consistency']
    cons_diff = abs(step3_cons - baseline_cons)

    # Print comparison table
    print("\n" + "="*80)
    print("Phase Transition Characteristics Comparison")
    print("="*80)

    print(f"\n{'Characteristic':<30} {'Step3':<15} {'Baseline':<15} {'Difference':<12} {'Status'}")
    print("-" * 85)

    # α_c comparison
    ac_status = "✅" if ac_diff <= alpha_tolerance else "❌"
    print(f"{'Phase Center (α_c)':<30} {step3_ac:<15.3f} {baseline_ac:<15.3f} {ac_diff:<12.3f} {ac_status}")

    # Gradient comparison
    grad_status = "✅" if grad_error <= gradient_tolerance else "❌"
    print(f"{'Max Gradient (dQ_Y/dα)':<30} {step3_grad:<15.4f} {baseline_grad:<15.4f} {grad_error*100:<11.2f}% {grad_status}")

    # Consistency comparison
    cons_status = "✅" if cons_diff <= 0.1 else "❌"
    print(f"{'Three-Metric Consistency':<30} {step3_cons:<15.4f} {baseline_cons:<15.4f} {cons_diff:<12.4f} {cons_status}")

    # Individual metric gradients
    print("\nIndividual Metric Gradients:")
    print(f"{'Metric':<30} {'Step3':<15} {'Baseline':<15} {'Error':<12} {'Status'}")
    print("-" * 85)

    metrics_pass = True
    for metric_key in ['Q_Y', 'Q_W_prime', 'Q_X_prime']:
        step3_val = step3_phase['all_gradients'].get(metric_key, 0.0)
        baseline_val = baseline_phase['all_gradients'].get(metric_key, 0.0)
        error = abs(step3_val - baseline_val) / baseline_val if baseline_val > 1e-6 else 0.0
        status = "✅" if error <= gradient_tolerance else "❌"
        if error > gradient_tolerance:
            metrics_pass = False
        print(f"{'d' + metric_key + '/dα':<30} {step3_val:<15.4f} {baseline_val:<15.4f} {error*100:<11.2f}% {status}")

    # Overall validation
    phase_pass = (ac_diff <= alpha_tolerance and
                  grad_error <= gradient_tolerance and
                  cons_diff <= 0.1 and
                  metrics_pass)

    print(f"\n{'='*80}")
    if phase_pass:
        print("✅ PHASE TRANSITION VALIDATION PASSED")
    else:
        print("❌ PHASE TRANSITION VALIDATION FAILED")
    print("="*80)

    return {
        'step3_phase': step3_phase,
        'baseline_phase': baseline_phase,
        'alpha_c_diff': ac_diff,
        'gradient_error': grad_error,
        'consistency_diff': cons_diff,
        'passed': phase_pass
    }


def main():
    """Main validation workflow"""
    print("="*80)
    print("STEP3 ADAPTIVE SAMPLING - 对拍 VALIDATION")
    print("="*80)
    print("\nThis script validates Step3 by comparing with Step2 baseline")
    print("using the SAME smart alphas generated by Step3.\n")

    # Paths
    base_dir = Path(__file__).parent
    smart_alphas_path = base_dir / "Result" / "200_200_50" / "smart_alphas.npy"
    step3_results_path = base_dir / "Result" / "200_200_50" / "results_step3_adaptive_coarse2000_fine20000.json"
    baseline_results_path = base_dir / "Result" / "200_200_50" / "results_baseline_smart_alphas_epoch20000.json"

    # Check if baseline results exist
    if not baseline_results_path.exists():
        print(f"\n⚠ Baseline results not found: {baseline_results_path}")
        print("\nYou need to run Step2 baseline with smart alphas first.")
        print("The baseline program should:")
        print("  1. Load smart_alphas.npy")
        print("  2. Run Step2 training with those 63 alphas")
        print("  3. Save results to results_baseline_smart_alphas_epoch20000.json")
        print("\nExiting validation...")
        return

    # Load data
    print("\n" + "="*80)
    print("LOADING DATA")
    print("="*80)

    smart_alphas = load_smart_alphas(smart_alphas_path)
    step3_results = load_results(step3_results_path)
    baseline_results = load_results(baseline_results_path)

    # Validation 1: Traditional point-by-point comparison
    traditional_result = traditional_comparison(step3_results, baseline_results, tolerance=0.10)

    # Validation 2: Phase transition comparison
    phase_result = phase_transition_comparison(step3_results, baseline_results,
                                              alpha_tolerance=0.2,
                                              gradient_tolerance=0.20)

    # Final summary
    print("\n" + "="*80)
    print("FINAL VALIDATION SUMMARY")
    print("="*80)

    print(f"\n✅ Traditional Validation: {'PASSED' if traditional_result['passed'] else 'FAILED'}")
    print(f"   - Max error: {traditional_result['max_error']*100:.2f}%")
    print(f"   - Mean error: {traditional_result['mean_error']*100:.2f}%")
    print(f"   - Points compared: {traditional_result['num_points']}")

    print(f"\n✅ Phase Transition Validation: {'PASSED' if phase_result['passed'] else 'FAILED'}")
    print(f"   - α_c difference: {phase_result['alpha_c_diff']:.3f}")
    print(f"   - Gradient error: {phase_result['gradient_error']*100:.2f}%")
    print(f"   - Consistency diff: {phase_result['consistency_diff']:.4f}")

    overall_pass = traditional_result['passed'] and phase_result['passed']

    print(f"\n{'='*80}")
    if overall_pass:
        print("🎉 OVERALL VALIDATION: ✅ PASSED")
        print("\nStep3 adaptive sampling is validated and ready for production!")
    else:
        print("⚠ OVERALL VALIDATION: ❌ FAILED")
        print("\nStep3 needs further investigation.")
    print("="*80)

    # Save validation report
    report_path = base_dir / "Result" / "200_200_50" / "validation_report.json"
    with open(report_path, 'w') as f:
        json.dump({
            'traditional': {
                'passed': traditional_result['passed'],
                'max_error': traditional_result['max_error'],
                'mean_error': traditional_result['mean_error'],
                'max_errors': traditional_result['max_errors']
            },
            'phase_transition': {
                'passed': phase_result['passed'],
                'alpha_c_diff': phase_result['alpha_c_diff'],
                'gradient_error': phase_result['gradient_error'],
                'consistency_diff': phase_result['consistency_diff']
            },
            'overall_passed': overall_pass
        }, f, indent=2)

    print(f"\n[Validation report saved] {report_path}")


if __name__ == "__main__":
    main()
